from byond-cdn


# Expose the shit
EXPOSE 2337

ENTRYPOINT ["DreamDaemon", "/byond-cdn/byond-cdn.dmb", "2337", "-trusted", "-params redirect_target=byond%3a%2f%2fbagil.game.tgstation13.org%3a2337"]