from byond-cdn


# Expose the shit
EXPOSE 1337

ENTRYPOINT ["DreamDaemon", "/byond-cdn/byond-cdn.dmb", "1337", "-trusted", "-params redirect_target=byond%3a%2f%2fsybil.game.tgstation13.org%3a1337"]